export const SUPPORTED_CHAINS = {
  ethereum: {
    id: "ethereum",
    name: "Ethereum",
    symbol: "ETH",
    chainId: 1,
    color: "#627EEA",
    bgColor: "bg-blue-500/10 border-blue-500/30 text-blue-400",
    badgeColor: "bg-[#627EEA]/20 text-[#8ea6ff] border-[#627EEA]/40",
    logo: "https://cryptologos.cc/logos/ethereum-eth-logo.svg?v=035",
    explorerUrl: "https://etherscan.io",
    rpcUrl: "https://eth.llamarpc.com",
    nativePriceUsd: 2850.0,
    tags: ["Bluechip NFTs", "DeFi", "Uniswap"]
  },
  base: {
    id: "base",
    name: "Base",
    symbol: "ETH",
    chainId: 8453,
    color: "#0052FF",
    bgColor: "bg-blue-600/10 border-blue-600/30 text-blue-400",
    badgeColor: "bg-[#0052FF]/20 text-[#6095ff] border-[#0052FF]/40",
    logo: "https://raw.githubusercontent.com/base-org/brand-kit/main/logo/in-product/Base_Symbol_Blue.svg",
    explorerUrl: "https://basescan.org",
    rpcUrl: "https://mainnet.base.org",
    nativePriceUsd: 2850.0,
    tags: ["Memecoins", "Aerodrome", "Friend.tech"]
  },
  hyperevm: {
    id: "hyperevm",
    name: "HyperEVM",
    symbol: "HYPE",
    chainId: 998,
    color: "#2EE59D",
    bgColor: "bg-emerald-500/10 border-emerald-500/30 text-emerald-400",
    badgeColor: "bg-[#2EE59D]/20 text-[#2EE59D] border-[#2EE59D]/40",
    logo: "https://pbs.twimg.com/profile_images/1691166318882041856/rYQkO2b5_400x400.jpg",
    explorerUrl: "https://hyperliquid.cloud.blockscout.com",
    rpcUrl: "https://rpc.hyperliquid.xyz/evm",
    nativePriceUsd: 38.5,
    tags: ["Hyperliquid", "Perps", "High-Speed"]
  },
  monad: {
    id: "monad",
    name: "Monad",
    symbol: "MON",
    chainId: 10143,
    color: "#836EF9",
    bgColor: "bg-purple-600/10 border-purple-600/30 text-purple-400",
    badgeColor: "bg-[#836EF9]/20 text-[#b5a7ff] border-[#836EF9]/40",
    logo: "https://pbs.twimg.com/profile_images/1769850125218320384/Q3J9x4xP_400x400.jpg",
    explorerUrl: "https://monadexplorer.com",
    rpcUrl: "https://testnet-rpc.monad.xyz",
    nativePriceUsd: 14.2,
    tags: ["Ultra-Speed 10k TPS", "Early Mints", "EVM Parallel"]
  },
  ink: {
    id: "ink",
    name: "Ink",
    symbol: "ETH",
    chainId: 57073,
    color: "#7B3FE4",
    bgColor: "bg-violet-600/10 border-violet-600/30 text-violet-400",
    badgeColor: "bg-[#7B3FE4]/20 text-[#c29eff] border-[#7B3FE4]/40",
    logo: "https://pbs.twimg.com/profile_images/1849479427672580096/QjD3Gv-E_400x400.jpg",
    explorerUrl: "https://explorer.inkonchain.com",
    rpcUrl: "https://rpc-gel.inkonchain.com",
    nativePriceUsd: 2850.0,
    tags: ["Kraken L2", "Superchain", "DeFi Hub"]
  },
  ape: {
    id: "ape",
    name: "ApeChain",
    symbol: "APE",
    chainId: 33139,
    color: "#0054F7",
    bgColor: "bg-blue-700/10 border-blue-700/30 text-blue-300",
    badgeColor: "bg-[#0054F7]/20 text-[#71a5ff] border-[#0054F7]/40",
    logo: "https://cryptologos.cc/logos/apecoin-ape-ape-logo.svg?v=035",
    explorerUrl: "https://apescan.io",
    rpcUrl: "https://apechain.calderachain.xyz/http",
    nativePriceUsd: 1.65,
    tags: ["Yuga Labs", "Gaming", "Ape NFTs"]
  },
  bnb: {
    id: "bnb",
    name: "BNB Chain",
    symbol: "BNB",
    chainId: 56,
    color: "#F0B90B",
    bgColor: "bg-yellow-500/10 border-yellow-500/30 text-yellow-400",
    badgeColor: "bg-[#F0B90B]/20 text-[#F0B90B] border-[#F0B90B]/40",
    logo: "https://cryptologos.cc/logos/bnb-bnb-logo.svg?v=035",
    explorerUrl: "https://bscscan.com",
    rpcUrl: "https://bsc-dataseed.binance.org",
    nativePriceUsd: 640.0,
    tags: ["PancakeSwap", "Altcoins", "Low Fees"]
  },
  arbitrum: {
    id: "arbitrum",
    name: "Arbitrum",
    symbol: "ETH",
    chainId: 42161,
    color: "#28A0F0",
    bgColor: "bg-cyan-500/10 border-cyan-500/30 text-cyan-400",
    badgeColor: "bg-[#28A0F0]/20 text-[#28A0F0] border-[#28A0F0]/40",
    logo: "https://cryptologos.cc/logos/arbitrum-arb-logo.svg?v=035",
    explorerUrl: "https://arbiscan.io",
    rpcUrl: "https://arb1.arbitrum.io/rpc",
    nativePriceUsd: 2850.0,
    tags: ["GMX", "DeFi Alpha", "Camelot"]
  },
  robinhood: {
    id: "robinhood",
    name: "Robinhood",
    symbol: "ETH",
    chainId: 4096,
    color: "#00C805",
    bgColor: "bg-green-500/10 border-green-500/30 text-green-400",
    badgeColor: "bg-[#00C805]/20 text-[#00C805] border-[#00C805]/40",
    logo: "https://cryptologos.cc/logos/robinhood-markets-hood-logo.svg?v=035",
    explorerUrl: "https://robinhood.com",
    rpcUrl: "https://rpc.robinhood.internal",
    nativePriceUsd: 2850.0,
    tags: ["Robinhood Chain", "Retail Alpha", "Zero Gas"]
  }
};
